"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
APP_NAME = "Glaze Additive Predictor"
APP_VERSION = "1.0.0"
DATA_FILES = ['res/icon.ico','res/logo.png','res/GLAZE_DATASET.xlsx']
OPTIONS = {
    'iconfile':'res/icon.ico',
    'plist': {
            'CFBundleName': APP_NAME,
            'CFBundleDisplayName': APP_NAME,
            'CFBundleGetInfoString': "Predicts the amount of CMC and Water to be added to adjust the parameters of Brown Glaze",
            'CFBundleIdentifier': "com.soujatya_sarkar.gap",
            'CFBundleVersion': APP_VERSION,
            'CFBundleShortVersionString': APP_VERSION,
            'NSHumanReadableCopyright': u"Copyright © 2022, Soujatya Sarkar, All Rights Reserved"
    }
}

setup(
    name=APP_NAME,
    version=APP_VERSION,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
